name: deploy-in-docker-mo-759

on:
  push:
    branches:
      - deploy-in-docker-mo-759

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Push and Deploy
    
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry:  ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: $IMAGE_TAG
